name: Tests
on:
  pull_request:
    branches:
      - main

jobs:
  bun_tests:
    name: Bun Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Navigation to typescript directory
        run: cd typescript

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install
        working-directory: typescript

      - name: Run test suites
        run: bun test
        working-directory: typescript

  go_tests:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Go Tests
        run: |
          cd go
          go test ./...
